@startuml

== 分享 ==

业务方 -> JoinImageClient : 请求拼图服务

JoinImageClient -> JoinImageCacheHelper : 请求缓存

JoinImageCacheHelper -> JoinImageClient : 存在缓存的话,返回cdnUrl

JoinImageClient -> 业务方 : 如果存在缓存直接返回cdnUrl

JoinImageClient -> JoinImageRpcService : 没有缓存,请求rpc服务去进行拼图逻辑

JoinImageRpcService -> JoinImageClient : 返回合成的图片的字节数组

JoinImageClient -> JoinImageClient : 如果合成失败 返回兜底图的字节数组
JoinImageClient -> KCdnService : 请求cdn服务 将字节数组存到cdn换取 cdnUrl 并缓存

JoinImageClient -> 业务方 : 返回cdnUrl
@enduml